openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact book
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Contact book app
tags:
  - name: Contacts
    description: Operations about contacts
servers:
  - url: http://localhost:3000
paths:
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
